# .render.yaml
services:
  - type: web
    name: ai-image-caption-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"